lab2_library/lab2_library/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using lab2_library.Models;

namespace lab2_library.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab2_library/lab2_library/Controllers/Lab2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lab2_library.Models;
using libr.Models;

namespace lab2_library.Controllers
{
    public class Lab2Controller : Controller
    {
        private readonly lab2_libraryContext _context;

        public Lab2Controller(lab2_libraryContext context)
        {
            _context = context;
        }

        // GET: Books
        [HttpGet]
        public async Task<IActionResult> GetBooks(string id)
        {
            var books = from b in _context.Book.Include(b => b.Jenre)
            select b;

            if (!String.IsNullOrEmpty(id))
            {
                books = books.Where(s => s.Name.Contains(id));
            }

            return View(await books.ToListAsync());
        }

        // GET: Readers
        [HttpGet]
        public async Task<IActionResult> GetReaders(string id)
        {
            var readers = from r in _context.Reader
                        select r;

            if (!String.IsNullOrEmpty(id))
            {
                readers = readers.Where(s => s.FullName.Contains(id));
            }

            return View(await readers.ToListAsync());
        }

        // GET: Jenres
        [HttpGet]
        public async Task<IActionResult> GetJenres(string id)
        {
            var jenres = from j in _context.Jenre
                          select j;

            if (!String.IsNullOrEmpty(id))
            {
                jenres = jenres.Where(s => s.Name.Contains(id));
            }

            return View(await jenres.ToListAsync());
        }


        // GET: Issuences
        [HttpGet]
        public async Task<IActionResult> GetIssuences(string id)
        {
            var issuences = from i in _context.Issuence.Include(i=>i.Reader).Include(i=>i.Book)
                         select i;

            if (!String.IsNullOrEmpty(id))
            {
                issuences = issuences.Where(s => s.Reader.FullName.Contains(id));
            }

            return View(await issuences.ToListAsync());
        }

        // GET: Books/Create
        public IActionResult CreateBook()
        {
            ViewData["JenreID"] = new SelectList(_context.Set<Jenre>(), "ID", "ID");
            return View();
        }

        // POST: Books/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateBook([Bind("ID,RegistrationNumber,Name,Author,Edition,YearOfEdition,JenreID,Price")] Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(GetBooks));
            }
            ViewData["JenreID"] = new SelectList(_context.Set<Jenre>(), "ID", "ID", book.JenreID);
            return View(book);
        }
    }
}

lab2_library/lab2_library/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<table class="table table-bordered" style="margin-top:10px;">
    <tr>
        <th>Action</th>
        <th>Link</th>
    </tr>
    <tr>
        <td>Create new book</td>
        <td><a href="Lab2/CreateBook" style="width:100px;" class="btn btn-primary">Create</a></td>
    </tr>
    @*<tr>
            <td>Get list of books</td>
            <td><a href="Lab2/GetBooks" style="width:100px;" class="btn btn-primary">Books</a></td>
        </tr>
        <tr>
            <td>Get list of readers</td>
            <td><a href="Lab2/GetReaders" style="width:100px;" class="btn btn-primary">Readers</a></td>
        </tr>
        <tr>
            <td>Get list of issuences</td>
            <td><a href="Lab2/GetIssuences" style="width:100px;" class="btn btn-primary">Journal</a></td>
        </tr>
        <tr>
            <td>Get list of Genres</td>
            <td><a href="Lab2/GetJenres" style="width:100px;" class="btn btn-primary">Genres</a></td>
        </tr>*@
    <tr>
        <td>Go to the html page</td>
        <td><a href="~/htmlpage.html" style="width:100px;" class="btn btn-primary">HTML</a></td>
    </tr>
    <tr>
        <td>LIST</td>
        <td>
            <ul>
                <li>1</li>
                <li>2</li>
                <li>3</li>
            </ul>
        </td>
    </tr>

</table>
    <img style="width:600px;" src="~/images/Picture.PNG">

lab2_library/lab2_library/Views/Lab2/CreateBook.cshtml
@model libr.Models.Book

@{
    ViewData["Title"] = "CreateBook";
}
<h2>CreateBook</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateBook">
            <label class="control-label">Registration Number </label>
            <input asp-for="RegistrationNumber" class="form-control" />

            <label class="control-label">Name </label>
            <input asp-for="Name" class="form-control" />

            <label class="control-label">Author </label>
            <input asp-for="Author" class="form-control" />

            <label class="control-label">Edition </label>
            <input asp-for="Edition" class="form-control" />

            <label class="control-label">Year Of Edition </label>
            <input asp-for="YearOfEdition" class="form-control" />

            <label class="control-label">Jenre </label>
            <input asp-for="JenreID" class="form-control" />

            <label class="control-label">Price </label>
            <input asp-for="Price" class="form-control" />
            <br />
            <input type="submit" value="Create" class="btn btn-primary" /> 
        </form>
    </div>
</div>

lab2_library/lab2_library/Views/Lab2/GetBooks.cshtml
@model IEnumerable<libr.Models.Book>
@{
    ViewData["Title"] = "Index";
}
<h2>Books</h2>
<img style="width:120px;" src="~/images/Picture.PNG" title="книга">

<form asp-controller="Lab2" asp-action="GetBooks">
    <p style="font-size:18px;">
        <b>Search by books: </b><input type="text" name="SearchString">
        <input class="btn btn-primary" type="submit" value="Filter" />

        <b>Search by genre: </b>
        <select>
    <option>Non-fiction</option>
    <option>Fiction</option>
    <option>Poetry</option>
    <option>Autobiographies</option>
    <option>Biographies</option>
    <option>History</option>
    <option>Science</option>
    <option>Drama</option>
    <option>Mystery</option>
    <option>Horror</option>
</select>
        <input class="btn btn-primary" type="submit" value="Filter" />
    </p>
</form>

<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RegistrationNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YearOfEdition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Jenre)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RegistrationNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Edition)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.YearOfEdition)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Jenre.Name)
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    LIST
    <ul>
        <li>1</li>
        <li>2</li>
        <li>3</li>
    </ul>
</div>

lab2_library/lab2_library/Views/Lab2/GetIssuences.cshtml
@model IEnumerable<libr.Models.Issuence>

@{
    ViewData["Title"] = "Index";
}

<h2>Issuences</h2>
<img style="width:120px;" src="~/images/Picture.PNG">

<form asp-controller="Lab2" asp-action="GetIssuences">
    <p style="font-size:18px;">
        <b>Search by reader: </b><input type="text" name="SearchString">
        <input class="btn btn-primary" type="submit" value="Filter" />
    <b>Search by book: </b>
    <select>
        @for (int i = 1; i < 10; i++) {
        <option>Book @i</option>
       }
    </select>
    <input class="btn btn-primary" type="submit" value="Filter" />
    </p>
</form>

<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateOfIssuance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfReturn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Return)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Book)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Reader)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfIssuance)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfReturn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Return)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Book.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Reader.FullName)
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    LIST
    <ul>
        <li>1</li>
        <li>2</li>
        <li>3</li>
    </ul>
</div>

lab2_library/lab2_library/Views/Lab2/GetJenres.cshtml
@model IEnumerable<libr.Models.Jenre>
@{
    ViewData["Title"] = "Index";
}
<h2>Genres</h2>
<img style="width:120px;" src="~/images/Picture.PNG">

<form asp-controller="Lab2" asp-action="GetJenres">
    <p style="font-size:18px;">
        <b>Search by genre: </b><input type="text" name="SearchString">
        <input class="btn btn-primary" type="submit" value="Filter" />
    </p>
</form>

<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    LIST
    <ul>
        <li>1</li>
        <li>2</li>
        <li>3</li>
    </ul>
</div>

lab2_library/lab2_library/Views/Lab2/GetReaders.cshtml
@model IEnumerable<libr.Models.Reader>
@{
    ViewData["Title"] = "Index";
}
<h2>Readers</h2>
    <img style="width:120px;" src="~/images/Picture.PNG" title="читатель">


    <form asp-controller="Lab2" asp-action="GetReaders">
        <p style="font-size:18px;">
            <b>Search by reader: </b> <input type="text" name="SearchString">
            <input class="btn btn-primary" type="submit" value="Filter" />

            <b>Search by year: </b>
            <select>
                @for (int i = 1950; i < 2010; i++)
                {
                    <option>@i</option>
                }
            </select>
            <input class="btn btn-primary" type="submit" value="Filter" />
        </p>
    </form>

    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FullName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateOfBirth)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Adres)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PassportData)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateOfBirth)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Adres)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PassportData)
                    </td>
                </tr>
            }

        </tbody>
    </table>

    <div>
        LIST
        <ul>
            <li>1</li>
            <li>2</li>
            <li>3</li>
        </ul>
    </div>

lab2_library/lab2_library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab2_library</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/htmlpage.html" class="navbar-brand">HTML</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Lab2" asp-action="GetBooks">Books</a></li>
                    <li><a asp-area="" asp-controller="Lab2" asp-action="GetReaders">Readers</a></li>
                    <li><a asp-area="" asp-controller="Lab2" asp-action="GetIssuences">Issuences</a></li>
                    <li><a asp-area="" asp-controller="Lab2" asp-action="GetJenres">Genres</a></li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Лабораторная №2 - Барсукова Надежда</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>